name: PyPI Release Notifier

on:
  schedule:
    - cron: "0 * * * *"  # Runs every hour
  workflow_dispatch:  # Allows manual triggering

jobs:
  check_release:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: main  # Fetch the default branch

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11.0"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Fetch state branch
        run: |
          git fetch origin state || git checkout --orphan state
          git checkout state || echo "No state branch exists, initializing."

      - name: Run notifier script
        env:
          PYPI_WEBHOOK_URL: ${{ secrets.PYPI_WEBHOOK_URL }}
          DISCORD_ROLE_ID: ${{ secrets.DISCORD_ROLE_ID }}
        run: python notifier.py
