name: PyPI Release Notifier

on:
  schedule:
    - cron: "0 * * * *"  # Runs every hour
  workflow_dispatch:  # Allows manual triggering

jobs:
  check_release:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11.0"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run notifier script
        env:
          PYPI_WEBHOOK_URL: ${{ secrets.PYPI_WEBHOOK_URL }}
          DISCORD_ROLE_ID: ${{ secrets.DISCORD_ROLE_ID }}
          LATEST_VERSION: ${{ vars.LATEST_VERSION }}  # Provide the last version to the script
        run: python notifier.py

      - name: Update LATEST_VERSION variable
        if: success()
        run: echo "LATEST_VERSION=${{ steps.set_env.outputs.latest_version }}" >> $GITHUB_ENV
